shapes with toolbar
Awesome-Diagrams/Awesome-diagrams pull request #10
Opened 2024-10-16 08:48 UTC by MetlinAlexander

2024-10-16 09:09 UTC, solloball approved these changes
В целом всё круто, только стоит наверно вынести типы shape'ов в какие нибудь классы, продумать архитектуру. Либо так зальём и потом кто-нибудь поправит это, либо позже можешь переделать

2024-10-16 09:09 UTC, solloball commented on frontend/app/internal/component/tools/ToolBar.tsx
> +    const constraints = new Box(0, 0, 1080, 720);
мб вынести этот constraints выше, и будем переиспользовать его?

2024-10-16 09:32 UTC, MetlinAlexander commented on frontend/app/internal/component/tools/ToolBar.tsx
> +    const constraints = new Box(0, 0, 1080, 720);
пофиксил, думаю позже уже архитектуру проработаем

2024-10-16 09:50 UTC, e-buzyurkin requested changes
Согласен с Кириллом насчет структуры. Надо что-то типа интерфейса джавовского сделать со стандартными методами типа ресайз, текст и тд, а потом имплементить в виде различных фигур(круг квадрат ...). Потом добавлять все фигуры в какой-то список и из этого списка пилить дропдаун меню. 

Оставлю пока метку request changes, если решим что это не относится к текущему, а отдельный пулл реквест, то аппрувну и замержу.

2024-11-13 06:59 UTC, solloball approved these changes

2024-11-13 06:59 UTC, merged