added outline rectangle
Awesome-Diagrams/Awesome-diagrams pull request #14
Opened 2024-11-08 16:57 UTC by e-buzyurkin

работает так: нажимаешь один раз на фигуру, появляется пунктирный прямоугольник, можешь водить фигуру как хочешь, потом надо нажать в свободном месте чтобы он пропал без прямоугольника водить фигуру нельзя

2024-11-09 06:11 UTC, solloball requested changes
В целом всё клёво, я думаю тебе стоит добавить в метод в интерфейс, остальное как считаешь нужным. В целом, мне кажется можно будет создать новую задачу на вынесения всей твоего логики из useCaseShapeв в другое место. Более того, нам нужен будет какой нибудь объект, который следит за всеми выбранными фигурами и их двигает, но опять же, это наверно другая задача

2024-11-09 06:11 UTC, solloball commented on frontend/app/internal/svg/svgShape/shapes/UseCaseShape.ts
> +    private selRectGapSize : number = 20;
вомзожно стоит будет сделать таску на перенос этого в конфиг какой нибудь

2024-11-09 06:11 UTC, solloball commented on frontend/app/internal/svg/svgShape/shapes/UseCaseShape.ts
> +        if (!this.group.node.contains(event.target as Node)) {
можно было написать if (this.group.node.contains(event.target as Node)) {return} и тогда вложенность снизилась, но это мелочи

2024-11-09 06:11 UTC, solloball commented on frontend/app/internal/svg/svgShape/shapes/UseCaseShape.ts
> +            this.draggable?.setDraggable(false);
стоит добавить setDraggable в интефейс, чтобы ошибок этих  не было

2024-11-10 08:50 UTC, e-buzyurkin commented on frontend/app/internal/svg/svgShape/movable/ConstraintMovable.ts
> +    constructor(shape: Shape | G, constraint: Box, selRectGapSize : number = 0) {
Если добавлять метод, то придется добавлять его и в интерфейс Movable, а он не особо относится к любому Movable. Поэтому конструктор звучит как меньшее из зол, если не нужно ограничивать размеры сonstraint, то просто не заполняешь аргумент и он ноль будет.

Если знаешь как это сделать без интерфейса, то тогда метод отличная идея.

2024-11-10 08:52 UTC, e-buzyurkin commented on frontend/app/internal/svg/svgShape/shapes/UseCaseShape.ts
> +    private selRectGapSize : number = 20;
Согласен, я правда не знаю как они работают в тайпскрипте

2024-11-10 08:53 UTC, e-buzyurkin commented on frontend/app/internal/svg/svgShape/shapes/UseCaseShape.ts
> +        if (!this.group.node.contains(event.target as Node)) {
ну тут вложенность 1 так что пофиг

2024-11-12 03:12 UTC, solloball commented on frontend/app/internal/svg/svgShape/movable/ConstraintMovable.ts
> +    constructor(shape: Shape | G, constraint: Box, selRectGapSize : number = 0) {
Я думал constructor(constraint) и статический метод calculate constraint(), а потом вызывать как нибудь так  constraint(calculate constraint(constraint, selRectGapSize)). Ещё можно сделать так constraint(constraint, selRectGapSize?: number). Из-за знака вопроса можно будет вызывать без selRectGapSize, он тогда будет undefined

2024-11-12 03:12 UTC, solloball approved these changes

2024-11-12 03:44 UTC, merged